---

- name: Check ansible version is suitable for this playbook
  assert:
    that: ansible_version.full | version_compare('2.1.4', '>=')
    msg: "Ansible version 2.1.4 or greater is required for this playbook"
  tags:
    - nginx
    - nginx-smoke-test
