---

- name: Ensure passlib library is installed
  package:
    name: python-passlib
    state: present
  tags:
    - nginx
    - nginx-htpasswd

- name: Create htpasswd file
  htpasswd:
    path: "{{ nginx_htpasswd_file }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: "{{ item.state | default('present') }}"
  no_log: true
  when: item.username is defined and item.password is defined
  with_items: "{{ nginx_htpasswd_users }}"
  tags:
    - nginx
    - nginx-htpasswd
